parameters:
  - name: SubscriptionConfiguration
    type: string
    default: $(sub-config-azure-cloud-test-resources)
  - name: SubscriptionConfigurations
    type: object
    default: null
  # EnvVars is used to help diagnose variable conflict issues early
  - name: EnvVars
    type: object
    default: null
  - name: SubscriptionConfigurationFilePath
    type: string
    default: ''
  - name: SubscriptionConfigurationFilePaths
    type: object
    default: null

steps:
  - pwsh: |
      $baseSubConfig = @'
        ${{ parameters.SubscriptionConfiguration }}
      '@ | ConvertFrom-Json -AsHashtable

      $subConfigJsons = @'
        ${{ convertToJson(parameters.SubscriptionConfigurations) }}
      '@ | ConvertFrom-Json -AsHashtable

      $baseSubConfigFilePath = '${{ parameters.SubscriptionConfigurationFilePath }}'

      $subConfigFiles = @'
        ${{ convertToJson(parameters.SubscriptionConfigurationFilePaths) }}
      '@ | ConvertFrom-Json -AsHashtable


      $subConfig = @{}
      if ($baseSubConfig) {
        $subConfig = SetSubscriptionConfiguration $baseSubConfig
      }

      if ($subConfigJsons) {
        foreach ($configJson in $subConfigJsons) {
          $config = $configJson | ConvertFrom-Json -AsHashtable
          $subConfig = UpdateSubscriptionConfiguration $subConfig $config
        }
      }

      if ($baseSubConfigFilePath) {
        $config = Get-Content $baseSubConfigFilePath | ConvertFrom-Json -AsHashtable
        $subConfig = UpdateSubscriptionConfiguration $subConfig $config
      }

      if ($subConfigFiles) {
        foreach ($configFilePath in $subConfigFiles) {
          $config = Get-Content $configFilePath | ConvertFrom-Json -AsHashtable
          $subConfig = UpdateSubscriptionConfiguration $subConfig $config
        }
      }

      Write-Host ($subConfig | ConvertTo-Json)
      $serialized = $subscriptionConfiguration | ConvertTo-Json -Compress
      Write-Host "##vso[task.setvariable variable=SubscriptionConfiguration;]$serialized"
    displayName: Merge subscription configurations
