# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/azure.resourcemanager.messagingconnectors/ci.mgmt.yml
    - sdk/azure.resourcemanager.messagingconnectors/sdk/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azure.resourcemanager.messagingconnectors
    LimitForPullRequest: true
    Artifacts:
    - name: sdk
      safeName: sdk
