# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none
pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/sustainablityservices/ci.mgmt.yml
    - sdk/sustainablityservices/Azure.ResourceManager.SustainabilityServices/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: sustainablityservices
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.SustainabilityServices
      safeName: AzureResourceManagerSustainabilityServices
