trigger: none

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    UseFederatedAuth: true
    ServiceDirectory: appconfiguration
    SupportedClouds: 'Public,Preview,UsGov'
