trigger: none

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: appconfiguration
    SupportedClouds: 'Public,Preview,UsGov'
    CloudConfig:
      Public:
        SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
        ServiceConnection: iso_azure-sdk-tests
        SubscriptionConfigurationFilePath: eng/common/TestResources/sub-config/AzurePublic.json
      Preview:
        SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
        ServiceConnection: azure-sdk-tests
      UsGov:
        SubscriptionConfiguration: $(sub-config-gov-test-resources)
        ServiceConnection: usgov_azure-sdk-tests
