trigger: none

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: communication
    Project: Azure.Communication.JobRouter
    UseFederatedAuth: true
    CloudConfig:
      Public:
        ServiceConnection: azure-sdk-tests
        SubscriptionConfigurationFilePaths:
          - eng/common/TestResources/sub-config/AzurePublicMsft.json
      Int:
        SubscriptionConfigurations:
          - $(sub-config-communication-int-test-resources-common)
          - $(sub-config-communication-int-test-resources-net)
    Clouds: Public,Int
    TestResourceDirectories:
      - communication/
