trigger: none
pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - tools/azure-plugin
  
extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
      - stage: 'Build'
        pool:
          name: azsdk-pool-mms-win-2022-general
          image: azsdk-pool-mms-win-2022-1espt
          os: windows
        jobs:
          - job: Build
            timeoutInMinutes: 120
            steps:
              - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
                parameters:
                  Paths:
                    - tools/azure-plugin
              - task: UseDotNet@2
                displayName: 'Use .NET Core SDK'
                retryCountOnTaskFailure: 3
                inputs:
                  useGlobalJson: true
                  performMultiLevelLookup: true
              - task: NodeTool@0
                displayName: "Install Node 18.x"
                inputs:
                  versionSpec: '18.x'
              - script: |
                  npm ci
                displayName: "Install packages"
                workingDirectory: $(Build.SourcesDirectory)/tools/azure-plugin
              - script: |
                  npm ls -a
                displayName: "List packages"
                workingDirectory: $(Build.SourcesDirectory)/tools/azure-plugin
              - script: |
                  npm run prettier
                displayName: "Emitter format check"
                workingDirectory: $(Build.SourcesDirectory)/tools/azure-plugin/emitter
              - script: |
                  npm run lint
                displayName: "Emitter linter check"
                workingDirectory: $(Build.SourcesDirectory)/tools/azure-plugin/emitter
              - task: Npm@1
                displayName: 'Build Azure csharp client emitter and generator'
                inputs:
                  command: custom
                  customCommand: run build
                  workingDir: $(Build.SourcesDirectory)/tools/azure-plugin              
              - task: PowerShell@2
                displayName: "Check if generated code is up-to-date"
                inputs:
                   filePath: $(Build.SourcesDirectory)/tools/azure-plugin/eng/scripts/CodeGenerationCheck.ps1
                env:
                  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
                  DOTNET_CLI_TELEMETRY_OPTOUT: 1
                  DOTNET_MULTILEVEL_LOOKUP: 0