# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/storage/
    exclude:
    - sdk/storage/Azure.ResourceManager.Storage/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/storage/
    exclude:
    - sdk/storage/Azure.ResourceManager.Storage/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: storage
    BuildSnippets: false
    ArtifactName: packages
    Artifacts:
    - name: Azure.Storage.Blobs
      safeName: AzureStorageBlobs
    - name: Azure.Storage.Blobs.Batch
      safeName: AzureStorageBlobsBatch
    - name: Azure.Storage.Common
      safeName: AzureStorageCommon
    - name: Azure.Storage.Files.Shares
      safeName: AzureStorageFilesShares
    - name: Azure.Storage.Files.DataLake
      safeName: AzureStorageFilesDataLake
    - name: Azure.Storage.Queues
      safeName: AzureStorageQueues
    TestSetupSteps:
    - template: /sdk/storage/tests-install-azurite.yml
