trigger: none

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: communication
    Project: Azure.Communication.Identity
    UseFederatedAuth: true
    CloudConfig:
      Public:
        ServiceConnection: azure-sdk-tests
        SubscriptionConfigurationFilePaths:
          - eng/common/TestResources/sub-config/AzurePublicMsft.json
        SubscriptionConfigurations:
          - $(sub-config-communication-services-cloud-test-identity-cte)
      PPE:
        ServiceConnection: azure-sdk-tests
        SubscriptionConfigurationFilePaths:
          - sdk/communication/communication-ppe-torus.json
      Int:
        SubscriptionConfigurations:
          - $(sub-config-communication-int-test-resources-common)
          - $(sub-config-communication-int-test-resources-net)
    Clouds: Public,PPE,Int
    TestResourceDirectories:
      - communication/



