# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none
pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/geocatalog/ci.mgmt.yml
    - sdk/geocatalog/Azure.ResourceManager.GeoCatalog/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: geocatalog
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.GeoCatalog
      safeName: AzureResourceManagerGeoCatalog
