# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/chaos
    - sdk/chaos/ci.yml
    - sdk/chaos/Azure.ResourceManager.Chaos

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/chaos
    - sdk/chaos/ci.yml
    - sdk/chaos/Azure.ResourceManager.Chaos

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: chaos
    ArtifactName: packages
    Artifacts:
    - name: Azure.ResourceManager.Chaos
      safeName: AzureResourceManagerChaos
